"""update company fields

Revision ID: 18dcd61c223e
Revises: 1d8eaa81cceb
Create Date: 2026-03-05 16:34:25.117155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18dcd61c223e'
down_revision: Union[str, Sequence[str], None] = '1d8eaa81cceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    # ### end Alembic commands ###
