"""add default to timestamps

Revision ID: 1d8eaa81cceb
Revises: 439e1a89022e
Create Date: 2026-02-27 00:24:06.496975

"""
from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d8eaa81cceb'
down_revision: Union[str, Sequence[str], None] = '439e1a89022e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa


def upgrade():
    # 1️⃣ Fill existing NULL values
    op.execute(
        "UPDATE companies SET updated_at = NOW() WHERE updated_at IS NULL;"
    )

    # 2️⃣ Now make it NOT NULL
    op.alter_column(
        'companies',
        'updated_at',
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False
    )

    op.alter_column(
        'companies',
        'created_at',
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
