"""add status to expenses

Revision ID: 4f9a362ea39b
Revises: 18dcd61c223e
Create Date: 2026-03-19 13:11:06.920376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f9a362ea39b'
down_revision: Union[str, Sequence[str], None] = '18dcd61c223e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_expense_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_constraint(op.f('budgets_company_id_category_id_month_year_key'), 'budgets', type_='unique')
    op.create_unique_constraint('unique_budget_per_month', 'budgets', ['company_id', 'category_id', 'month', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_budget_per_month', 'budgets', type_='unique')
    op.create_unique_constraint(op.f('budgets_company_id_category_id_month_year_key'), 'budgets', ['company_id', 'category_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.create_table('expenses',
    sa.Column('expense_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expense_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('expenses_category_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('expenses_company_id_fkey')),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.manager_id'], name=op.f('expenses_manager_id_fkey')),
    sa.PrimaryKeyConstraint('expense_id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('ix_expenses_expense_id'), 'expenses', ['expense_id'], unique=False)
    # ### end Alembic commands ###
